ALTER PROC PR_LISTA_ATENCAO_HIST @INICIO DATE, @FIM DATE,@QTDPORPAGINA INT ,@PAGINA INT
AS

DECLARE @INICIO DATE, @FIM DATE

SET @INICIO = '2022-10-01'
SET @FIM = '2022-10-30'


SET LANGUAGE 'Brazilian'
;with refs as (
	select distinct UPPER(DATENAME(MONTH,@INICIO)) "Mês Referência", CPF_CNPJ,CD_CLIENTE,NM_CLIENTE,
		   stuff ((SELECT DISTINCT '; ' + T.LISTA
					 from ST_LISTA_ATENCAO_HIST (nolock) as T
					 where T.CPF_CNPJ = I.CPF_CNPJ and
							t.DATA_GERACAO = i.DATA_GERACAO
					 for xml path('')),
				  1, 2, '') as "Listas Referência"
	  from ST_LISTA_ATENCAO_HIST (nolock) as I
	  WHERE DATA_GERACAO >= @INICIO
	  AND DATA_GERACAO <= @FIM
	 ) 

	,ants as( 
	SELECT DISTINCT  UPPER(DATENAME(MONTH,DATEADD(MONTH,-1 ,@INICIO))) "Mês Anterior",CPF_CNPJ,
		   STUFF ((SELECT DISTINCT '; ' + T.LISTA
					 FROM ST_LISTA_ATENCAO_HIST (nolock) AS T
					 WHERE T.CPF_CNPJ = I.CPF_CNPJ
					 AND  T.DATA_GERACAO = I.DATA_GERACAO
					 FOR XML PATH('')),
				  1, 2, '') AS "Listas Anteriores"
	FROM ST_LISTA_ATENCAO_HIST (nolock) AS I
	WHERE DATA_GERACAO >= DATEADD(MM, DATEDIFF(MM,0,@INICIO) - 1, 0) 
	AND DATA_GERACAO < (DATEADD(MONTH,-1 ,@FIM))


	  ) 

SELECT DISTINCT 

	 ISNULL([MÊS REFERÊNCIA], 'SEM REGISTRO') AS [MÊS REFERÊNCIA]
	,ISNULL(CD_CLIENTE , 'SEM REGISTRO') AS "CÓD. CLIENTE"
	,ISNULL(NM_CLIENTE, 'SEM REGISTRO') AS "NOME DO CLIENTE"
	,CAST(A.CPF_CNPJ AS FLOAT) AS "CPF/CNPJ"
	,ISNULL([LISTAS REFERÊNCIA], 'SEM REGISTRO') AS [LISTAS REFERÊNCIA]
	,ISNULL([MÊS ANTERIOR], 'SEM REGISTRO') AS [MÊS ANTERIOR]
	,ISNULL([LISTAS ANTERIORES], 'SEM REGISTRO') AS [LISTAS ANTERIORES]
	,CASE WHEN A.[LISTAS REFERÊNCIA] = B.[LISTAS ANTERIORES] THEN 'MANTINDO' ELSE 'ALTERADO'END AS STATUS

FROM REFS A
LEFT OUTER JOIN ANTS B
	ON A.CPF_CNPJ = B.CPF_CNPJ


ORDER BY 1
OFFSET (ISNULL(@PAGINA,1) - 1) * CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS
FETCH NEXT CASE WHEN  ISNULL(@QTDPORPAGINA,'') = '' THEN 100000000 ELSE @QTDPORPAGINA END ROWS ONLY;


